baseurl: "/color"
url: ""

collections:
  artists:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "artists"
    values:
      layout: "artist"
  - scope:
      path: ""
    values:
      layout: "default"